INSERT INTO `mp3s` VALUES(NULL, 'ac', "AC", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'battle', "Battle", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'battle_club', "Battle Club", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'beantown', "Beantown", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'beat_down', "Beat Down", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'beat_town', "Beat Town", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'big_thingz',"Big Thingz", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'black', "Black", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'blow_up_the_club',"Blow Up the Club", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'blue',"Blue", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'boston', "Boston", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'box_cutter',"Box Cutter", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'bullet_thrower', "Bullet Thrower", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'cali',"Cali", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'chicago',"Chicago", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'club_banga',"Club Banga", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'club_banga_ii',"Club Banga II", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'cmon',"Cmon", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'commrottery', "Commrottery", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'comp',"Comp", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'creepuponya', "Creepuponya", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'dance_hall',"Dance Hall", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'dark_ages', "Dark Ages", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'darkness', "Darkness", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'dead_army', "Dead Army", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'defcon_3', "Defcon 3", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'diesel', "Deisel", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'deliverance', "Deliverance", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'dieselist', "Dieselist", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'dont_fk_wit_tis', "Dont FK Wit Tis", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'dont_start',"Dont Start", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'eastcoast', "Eastcoast", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'eastcoast_banga', "Eastcoast Banga", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'eastcoast_ii', "Eastcoast II", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'eastcoast_iii',"Eastcoast III", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'eclipse',"Eclipse", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'fat_lip',"Fat Lip", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'fight', "Fight", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'find_yourself_dead', "Find Yourself Dead", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'fire_hotness', "Fire Hotness", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'force_of_chopped',"Force of Chopped", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'free',"Free", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'funk',"Funk", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'funk_ii',"Funk II", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'future_leads', "Future Leads", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'gansta', "Gangsta", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'gangsta_ii',"Gangsta II", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'gangsta_iii', "Gangsta III", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'gangsta_iv',"Gangsta IV", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'get_dough', "Get Dough", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'get_off',"Get Off", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'get_the_armor',"Get the Armor", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'goodness', "Goodness", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'grab_the_gat', "Grab the Gat", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'gun_style', "Gun Style", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'hang_tight',"Hang Tight", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'heavy_load',"Heavy Load", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'hella_good',"Hella Good", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'helltown', "Helltown", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'here_we_go',"Here We Go", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'hip_hop',"Hip Hop", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'honest', "Honest", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'honor_mega',"Honor Mega", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'hybrid', "Hybrid", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'hydra', "Hydra", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'innovator', "Innovator", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'irish_beat',"Irish Beat", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'jemima', "Jemima", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'joint_venture',"Joint Venture", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'kick_it',"Kick It", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'killa', "Killa", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'lawtown',"Lawtown", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'lovin_california',"Lovin California", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'mercury',"Mercury", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'miami', "Miami", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'mouth', "Mouth", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'my_money', "My Money", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'nolia_nightz', "Nolia Nightz", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'nuts',"Nuts", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'old_school',"Old School", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'old_school_gangsta', "Old School Gangsta", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'one_power', "One Power", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'pack_full_level', "Pack Full Level", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'pankakes', "Pankakes", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'pass_the_dutch', "Pass the Dutch", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'pride', "Pride", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'profit', "Profit", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'quit_while_u_ahead', "Quit While U Ahead", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'r_and_b',"R and B", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'red_eye',"Red Eye", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'reggaeton', "Reggaeton", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'rockin', "Rockin", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'rollcall', "Rollcall", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'royalty',"Royalty", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'sand_man', "Sand Man", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'shotgun',"Shotgun", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'slow_n_heavy', "Slow n Heavy", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'spit_fire', "Spit Fire", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'spit_start',"Spit Start", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'state_college',"State College", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'step_to_my_cypher', "Step to My Cypher", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'step_up',"Step Up", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'sure_enough', "Sure Enough", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'the_anthem',"The Anthem", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'the_beginning',"The Beginning", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'the_dead_zone',"The Dead Zone", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'three_two_fo', "Three Two Fo", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'ticonderoga', "Ticonderoga", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'true_child',"True Child", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'true_to_the_heart', "True to the Heart", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'try_to_get_the_money', "Try to Get the Money", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'twin_engines', "Twin Engines", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'violent_stomp',"Violent Stomp", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'want_it',"Want It", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'we_get_this', "We Get This", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'we_hot', "We Hot", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'westcoast', "Westcoast", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'westcoast_ii', "Westcoast II", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'westcoast_iii',"Westcoast III", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'westcoast_old_school', "Westcoast Old School", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'winningz', "Winningz", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'wont_do_you_no_good',"Wont Do You No Good", '', '', '', '1', 0);
INSERT INTO `mp3s` VALUES(NULL, 'yeah_what', "Yeah What", '', '', '', '1', 0);
																											 